// Code generated by tools/generate_integration_kit.py. DO NOT EDIT.

package cortexwebhooks

// Event type names, as Event.Type carries them.
const (
	EventActivationPortExecuted             = "activation.port_executed"
	EventCasesCaseOpened                    = "cases.case_opened"
	EventCasesCaseSlaBreached               = "cases.case_sla_breached"
	EventDunningStepTaken                   = "dunning.step_taken"
	EventIdentityPrincipalCreated           = "identity.principal_created"
	EventIdentityPrincipalSuspended         = "identity.principal_suspended"
	EventInvoicingInvoiceIssued             = "invoicing.invoice_issued"
	EventPaymentsPaymentFailed              = "payments.payment_failed"
	EventSubjectsSubjectCreated             = "subjects.subject_created"
	EventSubjectsSubjectErased              = "subjects.subject_erased"
	EventSubjectsSubjectReclassified        = "subjects.subject_reclassified"
	EventSubscriptionsSubscriptionSuspended = "subscriptions.subscription_suspended"
	EventWebhookPing                        = "webhook.ping"
)

// EventTypes is every type a receiver can be sent.
var EventTypes = []string{
	EventActivationPortExecuted,
	EventCasesCaseOpened,
	EventCasesCaseSlaBreached,
	EventDunningStepTaken,
	EventIdentityPrincipalCreated,
	EventIdentityPrincipalSuspended,
	EventInvoicingInvoiceIssued,
	EventPaymentsPaymentFailed,
	EventSubjectsSubjectCreated,
	EventSubjectsSubjectErased,
	EventSubjectsSubjectReclassified,
	EventSubscriptionsSubscriptionSuspended,
	EventWebhookPing,
}

// ActivationPortExecutedData is the data of activation.port_executed: A number moved between carriers on its execution day. `direction` says which way; a port out is the moment retention has lost the line.
type ActivationPortExecutedData struct {
	// The other carrier's code.
	CounterpartyCode string `json:"counterparty_code"`
	// in: the number arrived; out: it left for another carrier. One of: in, out.
	Direction string `json:"direction"`
	// The day the number moved.
	ExecutedOn string `json:"executed_on"`
	// The portability request's reference.
	PortReference string `json:"port_reference"`
	// The customer holding the line the port activated; null for a port with no order behind it, which names nobody.
	SubjectID *string `json:"subject_id"`
}

// CasesCaseOpenedData is the data of cases.case_opened: A customer case was raised and routed. Rules escalate by priority, category or queue.
type CasesCaseOpenedData struct {
	// The case's reference, as the case screens and API show it.
	CaseReference string `json:"case_reference"`
	// The tenant's own category code for the case.
	Category string `json:"category"`
	// How the case came in: phone, email, store, chat...
	Channel string `json:"channel"`
	// The case's priority. One of: high, low, normal, urgent.
	Priority string `json:"priority"`
	// The code of the queue the case was routed to.
	QueueCode string `json:"queue_code"`
	// The customer the fact concerns. Read them with GET /subjects/{id}.
	SubjectID string `json:"subject_id"`
}

// CasesCaseSlaBreachedData is the data of cases.case_sla_breached: A case ran past a service level it was promised -- first response or resolution. Published once per clock, when the sweep first finds it late.
type CasesCaseSlaBreachedData struct {
	// The case's reference, as the case screens and API show it.
	CaseReference string `json:"case_reference"`
	// The case's priority. One of: high, low, normal, urgent.
	Priority string `json:"priority"`
	// The code of the queue the case was routed to.
	QueueCode string `json:"queue_code"`
	// Which promise was missed. One of: first_response, resolution.
	SlaKind string `json:"sla_kind"`
	// The customer the fact concerns. Read them with GET /subjects/{id}.
	SubjectID string `json:"subject_id"`
}

// DunningStepTakenData is the data of dunning.step_taken: A collections case took a step of its schedule -- a reminder, a warning, a suspension. Once per step: the step's own row is what makes it exactly-once.
type DunningStepTakenData struct {
	// What the step did. One of: refer, remind, suspend, warn, write_off.
	Action string `json:"action"`
	// The collections case's reference.
	CaseReference string `json:"case_reference"`
	// How late the debt was when the step ran.
	DaysOverdue int64 `json:"days_overdue"`
	// Which step of the schedule, from 1.
	StepNo int64 `json:"step_no"`
	// The customer the fact concerns. Read them with GET /subjects/{id}.
	SubjectID string `json:"subject_id"`
}

// IdentityPrincipalCreatedData is the data of identity.principal_created: A principal now exists. Consumers may provision module-local records for them.
type IdentityPrincipalCreatedData struct {
	// Which kind of account: staff, leadership, administrator, a customer's own or a machine identity. One of: administrator, client, employee, manager, service.
	BaseKind string `json:"base_kind"`
	// The new account.
	PrincipalID string `json:"principal_id"`
}

// IdentityPrincipalSuspendedData is the data of identity.principal_suspended: A principal's access was withdrawn. Consumers reassign their work and close sessions.
type IdentityPrincipalSuspendedData struct {
	// The account whose access was withdrawn.
	PrincipalID string `json:"principal_id"`
	// A machine code, status_changed_to_<status>. Never free text.
	Reason string `json:"reason"`
}

// InvoicingInvoiceIssuedData is the data of invoicing.invoice_issued: A customer's document for a cycle was numbered and sealed -- an invoice, or a statement when an offer took the whole bill. Rules watch large bills and warn before a charge.
type InvoicingInvoiceIssuedData struct {
	// ISO 4217 code of the amount.
	CurrencyCode string `json:"currency_code"`
	// The billing cycle the document closes.
	CycleReference string `json:"cycle_reference"`
	// When payment is due.
	DueOn string `json:"due_on"`
	// The document's number: fiscal for an invoice or a credit note, from the statements' own series for a statement.
	InvoiceReference string `json:"invoice_reference"`
	// An invoice, a credit note, or a statement that demands nothing. One of: credit_note, invoice, statement.
	Kind string `json:"kind"`
	// The customer the fact concerns. Read them with GET /subjects/{id}.
	SubjectID string `json:"subject_id"`
	// An amount in minor units of currency_code -- cents, centavos.
	TotalMinor int64 `json:"total_minor"`
}

// PaymentsPaymentFailedData is the data of payments.payment_failed: A gateway declined a charge. Not published for an unknown outcome: a charge nobody answered for may have landed. Rules raise a follow-up for collections.
type PaymentsPaymentFailedData struct {
	// An amount in minor units of currency_code -- cents, centavos.
	AmountMinor int64 `json:"amount_minor"`
	// The attempt's idempotency key, unique per charge attempt.
	AttemptKey string `json:"attempt_key"`
	// ISO 4217 code of the amount.
	CurrencyCode string `json:"currency_code"`
	// Why the gateway declined, as a closed code. One of: declined, expired, insufficient_funds, invalid_request, suspected_fraud, unavailable.
	FailureCode string `json:"failure_code"`
	// The invoice the charge was for; null for a charge against no invoice.
	InvoiceReference *string `json:"invoice_reference"`
	// Whether retrying the same method later is sensible.
	Retryable bool `json:"retryable"`
	// The customer the fact concerns. Read them with GET /subjects/{id}.
	SubjectID string `json:"subject_id"`
}

// SubjectsSubjectCreatedData is the data of subjects.subject_created: A subject record was opened. Consumers may begin holding data against it.
type SubjectsSubjectCreatedData struct {
	// A person or an organisation. One of: organisation, person.
	Kind string `json:"kind"`
	// The customer the fact concerns. Read them with GET /subjects/{id}.
	SubjectID string `json:"subject_id"`
}

// SubjectsSubjectErasedData is the data of subjects.subject_erased: A subject exercised erasure. Every consumer holding derived identifying data must destroy it — this is the event that makes a right to be forgotten reach modules that never owned the record.
type SubjectsSubjectErasedData struct {
	// The customer the fact concerns. Read them with GET /subjects/{id}.
	SubjectID string `json:"subject_id"`
}

// SubjectsSubjectReclassifiedData is the data of subjects.subject_reclassified: A subject's data classification changed. Consumers re-evaluate their handling rules.
type SubjectsSubjectReclassifiedData struct {
	// The sensitivity the customer's record is now handled at. One of: confidential, internal, public, restricted.
	Classification string `json:"classification"`
	// The customer the fact concerns. Read them with GET /subjects/{id}.
	SubjectID string `json:"subject_id"`
}

// SubscriptionsSubscriptionSuspendedData is the data of subscriptions.subscription_suspended: A hold was placed on a line -- for credit, fraud, a customer's request or a lost handset. Rules raise a follow-up for retention or collections.
type SubscriptionsSubscriptionSuspendedData struct {
	// outgoing bars calls and data the customer makes; full bars everything. One of: full, outgoing.
	Barring string `json:"barring"`
	// Why: non-payment, the customer's request, fraud, theft or a regulator. One of: customer_request, fraud, non_payment, regulatory, theft.
	Kind string `json:"kind"`
	// The customer the fact concerns. Read them with GET /subjects/{id}.
	SubjectID string `json:"subject_id"`
	// The line or service that was barred.
	SubscriptionReference string `json:"subscription_reference"`
}

// WebhookPingData is the data of webhook.ping, sent to check a receiver end to end.
type WebhookPingData struct {
	EndpointReference string `json:"endpoint_reference"`
}
