"""The events Cortex sends, as types.

Generated by tools/generate_integration_kit.py from the platform's own code. Do not edit.
"""

from __future__ import annotations

from typing import Final, Literal, TypedDict


class ActivationPortExecutedData(TypedDict):
    """A number moved between carriers on its execution day. `direction` says which way; a port out
    is the moment retention has lost the line.
    """

    #: The other carrier's code.
    counterparty_code: str
    #: in: the number arrived; out: it left for another carrier.
    direction: Literal["in", "out"]
    #: The day the number moved.
    executed_on: str
    #: The portability request's reference.
    port_reference: str
    #: The customer holding the line the port activated; null for a port with no order behind it,
    #: which names nobody.
    subject_id: str | None


class ActivationPortExecuted(TypedDict):
    type: Literal["activation.port_executed"]
    timestamp: str
    schema_version: Literal[1]
    data: ActivationPortExecutedData


class CasesCaseOpenedData(TypedDict):
    """A customer case was raised and routed. Rules escalate by priority, category or queue."""

    #: The case's reference, as the case screens and API show it.
    case_reference: str
    #: The tenant's own category code for the case.
    category: str
    #: How the case came in: phone, email, store, chat...
    channel: str
    #: The case's priority.
    priority: Literal["high", "low", "normal", "urgent"]
    #: The code of the queue the case was routed to.
    queue_code: str
    #: The customer the fact concerns. Read them with GET /subjects/{id}.
    subject_id: str


class CasesCaseOpened(TypedDict):
    type: Literal["cases.case_opened"]
    timestamp: str
    schema_version: Literal[1]
    data: CasesCaseOpenedData


class CasesCaseSlaBreachedData(TypedDict):
    """A case ran past a service level it was promised -- first response or resolution. Published
    once per clock, when the sweep first finds it late.
    """

    #: The case's reference, as the case screens and API show it.
    case_reference: str
    #: The case's priority.
    priority: Literal["high", "low", "normal", "urgent"]
    #: The code of the queue the case was routed to.
    queue_code: str
    #: Which promise was missed.
    sla_kind: Literal["first_response", "resolution"]
    #: The customer the fact concerns. Read them with GET /subjects/{id}.
    subject_id: str


class CasesCaseSlaBreached(TypedDict):
    type: Literal["cases.case_sla_breached"]
    timestamp: str
    schema_version: Literal[1]
    data: CasesCaseSlaBreachedData


class DunningStepTakenData(TypedDict):
    """A collections case took a step of its schedule -- a reminder, a warning, a suspension. Once
    per step: the step's own row is what makes it exactly-once.
    """

    #: What the step did.
    action: Literal["refer", "remind", "suspend", "warn", "write_off"]
    #: The collections case's reference.
    case_reference: str
    #: How late the debt was when the step ran.
    days_overdue: int
    #: Which step of the schedule, from 1.
    step_no: int
    #: The customer the fact concerns. Read them with GET /subjects/{id}.
    subject_id: str


class DunningStepTaken(TypedDict):
    type: Literal["dunning.step_taken"]
    timestamp: str
    schema_version: Literal[1]
    data: DunningStepTakenData


class IdentityPrincipalCreatedData(TypedDict):
    """A principal now exists. Consumers may provision module-local records for them."""

    #: Which kind of account: staff, leadership, administrator, a customer's own or a machine
    #: identity.
    base_kind: Literal["administrator", "client", "employee", "manager", "service"]
    #: The new account.
    principal_id: str


class IdentityPrincipalCreated(TypedDict):
    type: Literal["identity.principal_created"]
    timestamp: str
    schema_version: Literal[1]
    data: IdentityPrincipalCreatedData


class IdentityPrincipalSuspendedData(TypedDict):
    """A principal's access was withdrawn. Consumers reassign their work and close sessions."""

    #: The account whose access was withdrawn.
    principal_id: str
    #: A machine code, status_changed_to_<status>. Never free text.
    reason: str


class IdentityPrincipalSuspended(TypedDict):
    type: Literal["identity.principal_suspended"]
    timestamp: str
    schema_version: Literal[1]
    data: IdentityPrincipalSuspendedData


class InvoicingInvoiceIssuedData(TypedDict):
    """A customer's document for a cycle was numbered and sealed -- an invoice, or a statement when
    an offer took the whole bill. Rules watch large bills and warn before a charge.
    """

    #: ISO 4217 code of the amount.
    currency_code: str
    #: The billing cycle the document closes.
    cycle_reference: str
    #: When payment is due.
    due_on: str
    #: The document's number: fiscal for an invoice or a credit note, from the statements' own
    #: series for a statement.
    invoice_reference: str
    #: An invoice, a credit note, or a statement that demands nothing.
    kind: Literal["credit_note", "invoice", "statement"]
    #: The customer the fact concerns. Read them with GET /subjects/{id}.
    subject_id: str
    #: An amount in minor units of currency_code -- cents, centavos.
    total_minor: int


class InvoicingInvoiceIssued(TypedDict):
    type: Literal["invoicing.invoice_issued"]
    timestamp: str
    schema_version: Literal[1]
    data: InvoicingInvoiceIssuedData


class PaymentsPaymentFailedData(TypedDict):
    """A gateway declined a charge. Not published for an unknown outcome: a charge nobody answered
    for may have landed. Rules raise a follow-up for collections.
    """

    #: An amount in minor units of currency_code -- cents, centavos.
    amount_minor: int
    #: The attempt's idempotency key, unique per charge attempt.
    attempt_key: str
    #: ISO 4217 code of the amount.
    currency_code: str
    #: Why the gateway declined, as a closed code.
    failure_code: Literal[
        "declined",
        "expired",
        "insufficient_funds",
        "invalid_request",
        "suspected_fraud",
        "unavailable",
    ]
    #: The invoice the charge was for; null for a charge against no invoice.
    invoice_reference: str | None
    #: Whether retrying the same method later is sensible.
    retryable: bool
    #: The customer the fact concerns. Read them with GET /subjects/{id}.
    subject_id: str


class PaymentsPaymentFailed(TypedDict):
    type: Literal["payments.payment_failed"]
    timestamp: str
    schema_version: Literal[1]
    data: PaymentsPaymentFailedData


class SubjectsSubjectCreatedData(TypedDict):
    """A subject record was opened. Consumers may begin holding data against it."""

    #: A person or an organisation.
    kind: Literal["organisation", "person"]
    #: The customer the fact concerns. Read them with GET /subjects/{id}.
    subject_id: str


class SubjectsSubjectCreated(TypedDict):
    type: Literal["subjects.subject_created"]
    timestamp: str
    schema_version: Literal[1]
    data: SubjectsSubjectCreatedData


class SubjectsSubjectErasedData(TypedDict):
    """A subject exercised erasure. Every consumer holding derived identifying data must destroy it
    — this is the event that makes a right to be forgotten reach modules that never owned the
    record.
    """

    #: The customer the fact concerns. Read them with GET /subjects/{id}.
    subject_id: str


class SubjectsSubjectErased(TypedDict):
    type: Literal["subjects.subject_erased"]
    timestamp: str
    schema_version: Literal[1]
    data: SubjectsSubjectErasedData


class SubjectsSubjectReclassifiedData(TypedDict):
    """A subject's data classification changed. Consumers re-evaluate their handling rules."""

    #: The sensitivity the customer's record is now handled at.
    classification: Literal["confidential", "internal", "public", "restricted"]
    #: The customer the fact concerns. Read them with GET /subjects/{id}.
    subject_id: str


class SubjectsSubjectReclassified(TypedDict):
    type: Literal["subjects.subject_reclassified"]
    timestamp: str
    schema_version: Literal[1]
    data: SubjectsSubjectReclassifiedData


class SubscriptionsSubscriptionSuspendedData(TypedDict):
    """A hold was placed on a line -- for credit, fraud, a customer's request or a lost handset.
    Rules raise a follow-up for retention or collections.
    """

    #: outgoing bars calls and data the customer makes; full bars everything.
    barring: Literal["full", "outgoing"]
    #: Why: non-payment, the customer's request, fraud, theft or a regulator.
    kind: Literal["customer_request", "fraud", "non_payment", "regulatory", "theft"]
    #: The customer the fact concerns. Read them with GET /subjects/{id}.
    subject_id: str
    #: The line or service that was barred.
    subscription_reference: str


class SubscriptionsSubscriptionSuspended(TypedDict):
    type: Literal["subscriptions.subscription_suspended"]
    timestamp: str
    schema_version: Literal[1]
    data: SubscriptionsSubscriptionSuspendedData


class WebhookPingData(TypedDict):
    endpoint_reference: str


class WebhookPing(TypedDict):
    """Sent from the integrations screen to check a receiver end to end."""

    type: Literal["webhook.ping"]
    timestamp: str
    schema_version: Literal[1]
    data: WebhookPingData


Event = (
    ActivationPortExecuted
    | CasesCaseOpened
    | CasesCaseSlaBreached
    | DunningStepTaken
    | IdentityPrincipalCreated
    | IdentityPrincipalSuspended
    | InvoicingInvoiceIssued
    | PaymentsPaymentFailed
    | SubjectsSubjectCreated
    | SubjectsSubjectErased
    | SubjectsSubjectReclassified
    | SubscriptionsSubscriptionSuspended
    | WebhookPing
)

#: Every type a receiver can be sent.
EVENT_TYPES: Final = frozenset(
    {
        "activation.port_executed",
        "cases.case_opened",
        "cases.case_sla_breached",
        "dunning.step_taken",
        "identity.principal_created",
        "identity.principal_suspended",
        "invoicing.invoice_issued",
        "payments.payment_failed",
        "subjects.subject_created",
        "subjects.subject_erased",
        "subjects.subject_reclassified",
        "subscriptions.subscription_suspended",
        "webhook.ping",
    }
)
