/**
 * The TypeScript verifier against the vectors the platform signed (`../../vectors.json`).
 *
 * The vectors are generated by the platform's own signing code, so passing them means this
 * verifier accepts what Cortex actually sends and refuses what it must -- not merely that it
 * agrees with a description of the scheme.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";

import { EVENT_TYPES, verify, WebhookVerificationError } from "../src/index.ts";

interface Vector {
  readonly name: string;
  readonly secret: string;
  readonly headers: Readonly<Record<string, string>>;
  readonly body: string;
  readonly now: number;
  readonly expect: { readonly ok: true; readonly type: string } | { readonly ok: false; readonly reason: string };
}

const VECTORS = JSON.parse(
  readFileSync(new URL("../../vectors.json", import.meta.url), "utf8"),
) as { readonly vectors: readonly Vector[]; readonly event_types: readonly string[] };

describe("the TypeScript verifier", () => {
  for (const vector of VECTORS.vectors) {
    it(vector.name, () => {
      if (vector.expect.ok) {
        const event = verify(vector.secret, vector.headers, vector.body, { now: vector.now });
        assert.equal(event.type, vector.expect.type);
      } else {
        const reason = vector.expect.reason;
        assert.throws(
          () => verify(vector.secret, vector.headers, vector.body, { now: vector.now }),
          (error: unknown) => error instanceof WebhookVerificationError && error.reason === reason,
        );
      }
    });
  }

  it("knows every event type the platform publishes", () => {
    assert.deepEqual([...EVENT_TYPES].sort(), [...VECTORS.event_types].sort());
  });

  it("reads headers from a Fetch Headers object as well as a plain record", () => {
    const vector = VECTORS.vectors.find((each) => each.expect.ok);
    assert.ok(vector);
    const event = verify(vector.secret, new Headers(vector.headers), vector.body, {
      now: vector.now,
    });
    assert.ok(event.type.length > 0);
  });
});
